name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgl-dev
        sudo apt-get install libgtk-3-dev
        sudo apt-get install librsvg2-bin
    - name: Compile
      run: make
